version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/0.sql"

volumes:
  postgres-data: