# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/0.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres-data: